use_frameworks!

target 'CXSwiftCommonModule_Example' do
  platform :ios, '10.0'
  pod 'CXSwiftCommonModule', :path => '../'
  # IGListKit
  pod 'IGListKit', '4.0.0'
  # UserDefaults二次封装
  pod 'DefaultsKit'
  # Snapkit
  pod 'SnapKit', '4.2.0'
  # 键盘管理
  pod 'IQKeyboardManager', '6.5.6'
  # TabController
  pod "ESTabBarController-swift"
  # 布局
  pod 'Yoga'
  pod 'FlexLayout'
  pod 'PinLayout'

  target 'CXSwiftCommonModule_Tests' do
    inherit! :search_paths

  end
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
        end
      end
    end
end
